#!/bin/bash
#do_run=1 # Execute(evaluate) the commands
do_run=0 # Don't evaluate any commands
force=$2
if [ "$#" -eq 2 ]; then
  if [ $force = "-f" ]; then
    do_run=1
  fi
fi
while read org
do

#curl $accountsurl/accounts/v1/subaccounts --silent --location --insecure --request POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer '$bearer --data-raw '{"betaEnabled": true, "customProperties": [ { "key": "creator", "value": "primaryuser03" } ], "description": "Subaccount created via API", "displayName": "ViaAPI", "parentGUID": "'$globalacctguid'", "region": "us21", "subaccountAdmins": [ "andrew.lunde@sap.com" ], "subdomain": "viaapi", "usedForProductionSetting": "USED_FOR_PRODUCTION"}' | jq .

echo "Creating SubAccount : $org "
cmd='curl $accountsurl/accounts/v1/subaccounts --silent --location --insecure --request POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer '$bearer --data-raw '{"betaEnabled": true, "customProperties": [ { "key": "creator", "value": "primaryuser03" } ], "description": "Subaccount created via API", "displayName": "ViaAPI", "parentGUID": "'$globalacctguid'", "region": "us21", "subaccountAdmins": [ "andrew.lunde@sap.com" ], "subdomain": "viaapi", "usedForProductionSetting": "USED_FOR_PRODUCTION"}' | jq .'

echo $cmd
if [ $do_run -eq 1 ]; then eval $cmd; fi
echo ""


echo "Creating Org : x$org "
cmd='cf create-org x'$org''

echo $cmd
if [ $do_run -eq 1 ]; then eval $cmd; fi
echo ""


space=dev
echo "Creating Space : $space in $org"
cmd='cf create-space '$space' -o '$org''
echo $cmd
if [ $do_run -eq 1 ]; then eval $cmd; fi
echo ""

done < $1
